### ISSUE TITLE
Make the package tree-shakable

### ISSUE THREAD

**Issue by mesqueeb** [urin/qrono#1]
I see you opted for a chain-able syntax like so:
```js
qrono('2021-08-31 12:34')
  .plus({ month: 1 })
  .isSame(qrono('2021-09-30 12:34'))
```
However, when a developer eg. doesn't use `isSame` I believe it's still imported in into his bundle?

I believe that a chainable-syntax is not tree-shakable.

Not sure you're interested in tree-shaking if it would require your whole syntax to change to a more functional approach with just functions. (see date-fns for inspiration)
But I just though I'd throw it out here. : D

Feel free to close!

**Comment by urin** [comment]
Thanks for the comment. 👍 
I believe qrono will be kept so small that anyone does not need tree-shaking and it is the purpose of this library.
That's why qrono does not support multiple timezones and locales.
